### ISSUE TITLE
log and exit is broken

### ISSUE THREAD

**Issue by depwl9992** [dmkilday/GameMaster-GPT#13]
```
Player: Continue onward!!
Invalid request to OpenAI API: This model's maximum context length is 4097 tokens. However, your messages resulted in 4177 tokens. Please reduce the length of the messages.
Player: log and exit
Traceback (most recent call last):
  File "D:\My Programs\GameMaster-GPT\gm-gpt.py", line 349, in <module>
    start_new_adventure()
  File "D:\My Programs\GameMaster-GPT\gm-gpt.py", line 209, in start_new_adventure
    if log_file_name == "":
       ^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'log_file_name' where it is not associated with a value
```

I'm guessing something with the refactoring was missed..

**Comment by dmkilday** [comment]
Sorry...I probably broke this. Note, i changed the log directory name from "Logs" to "log". I did the same thing with Data.
